--- Image EXIF preview using exiftool.
--- Shows the actual image + themed EXIF metadata below.

local M = {}

local function is_binary_data(line)
	return line:find("(Binary data", 1, true) ~= nil
		or line:find("Tone Reproduction Curve", 1, true) ~= nil
end

local MAGICK_MIMES = {
	avif = true, hei = true, heic = true, heif = true,
	jxl = true, tiff = true, xml = true,
}

local function preload_image(job)
	local mime = job.mime and job.mime:match(".*/(.*)$")
	if not mime then
		return nil
	end

	local mod
	if mime == "svg+xml" then
		mod = "svg"
	elseif MAGICK_MIMES[mime] then
		mod = "magick"
	else
		mod = "image"
	end

	return require(mod):preload({ skip = 0, file = job.file, args = job.args, area = job.area })
end

function M:peek(job)
	-- 1. Preload thumbnail (ignore errors, will try fallback below)
	local _, _ = preload_image(job)

	-- 2. Try cached image first, fallback to original URL
	local cache = ya.file_cache({ skip = 0, file = job.file, args = job.args, area = job.area })
	local img_h = 0

	if cache and fs.cha(cache) and (fs.cha(cache).len or 0) > 0 then
		-- Cached image exists (generated by image/svg/magick module)
		local r = ya.image_show(cache, ui.Rect {
			x = job.area.x, y = job.area.y,
			w = job.area.w, h = math.floor(job.area.h * 0.5),
		})
		if r then img_h = r.h end
	end

	if img_h == 0 then
		-- Fallback: show original file directly
		local r = ya.image_show(job.file.url, ui.Rect {
			x = job.area.x, y = job.area.y,
			w = job.area.w, h = math.floor(job.area.h * 0.5),
		})
		if r then img_h = r.h end
	end

	-- 3. Run exiftool for EXIF text
	local child = Command("exiftool")
		:arg({ tostring(job.file.url) })
		:stdout(Command.PIPED)
		:stderr(Command.NULL)
		:spawn()
	if not child then
		return
	end

	local text_h = math.max(1, job.area.h - img_h)
	local i, lines = 0, {}
	repeat
		local raw, ev = child:read_line()
		if ev == 1 then
			return
		elseif ev ~= 0 then
			break
		end
		if is_binary_data(raw) then
			goto skip
		end

		i = i + 1
		if i > job.skip then
			local label, val = raw:match("^(.-)  +: (.*)")
			if label then
				table.insert(lines, ui.Line {
					ui.Span(label .. ":  "):style(ui.Style():bold()),
					ui.Span(val):style(th.spot.tbl_col or ui.Style():fg("blue")),
				})
			else
				table.insert(lines, ui.Line(ui.Span(raw)))
			end
		end
		::skip::
	until i >= job.skip + text_h
	child:wait()

	if #lines == 0 and job.skip > 0 then
		ya.manager_emit("peek", {
			tostring(math.max(0, job.skip - text_h)),
			only_if = tostring(job.file.url),
			upper_bound = true,
		})
		return
	end

	ya.preview_widget(job, {
		ui.Text(lines):area(ui.Rect {
			x = job.area.x, y = job.area.y + img_h,
			w = job.area.w, h = text_h,
		}):wrap(ui.Wrap.YES),
	})
end

function M:seek(job)
	local h = cx.active.current.hovered
	if h and h.url == job.file.url then
		ya.manager_emit("peek", {
			tostring(math.max(0, cx.active.preview.skip + job.units)),
			only_if = tostring(job.file.url),
		})
	end
end

return M
